### PR TITLE
Fix readme link

### PR DESCRIPTION
**Pull request by GUIpsp**

### CODE REVIEW

**Comment by GUIpsp** [comment]
This is such a minor change that I didn't bother signing it. Hopefully that's ok.

**Comment by 4tXJ7f** [comment]
Thank you for the PR. This may seem unnecessary, but it would still be great if you could sign your commit despite this being a minor change. The issue is that we want to keep our rules simple and don't want to start deciding what is minor enough and what isn't. I hope that that makes sense.

**Comment by 4tXJ7f** [comment]
@GUIpsp, I somehow can't see the `Signed-off-by:` line in the commit message. Am I missing something? Thanks.

**Comment by aniemetz** [comment]
Obsolete with #7222.

**Pull request closed without merging**
