### PR TITLE
Fix unsat core proofs

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes cases of satisfiable unsat cores when proofs are enabled.

Unfortunately, this bug was also preventing us from doing the final scope check for all proof checking.  As this was not being tested, this PR uncovers that proof checking is now failing on 6 regressions.  I'm disabling proof checking here and will address these issues on later PRs.

### CODE REVIEW

**Review by mpreiner — APPROVED** [review]
LGTM, does this fix #6625 ?

**Comment by 4tXJ7f** [comment]
I briefly tested it and it looks like it does fix #6625.

**Comment by HanielB** [comment]
Why ensuring that the proof is closed fixes the problem with that regression?

**Comment by ajreynol** [comment]
The "ensureClosed" argument makes sure that the proof is processed in a way that connects its free assumptions to the arguments of the final scope. If this is not done, then (= x y) could be a free assumption where (= y x) is an input assumption, and hence (= y x) would not be included in the unsat core.

**Pull request merged**
