### PR TITLE
Correct FindCaDiCaL.cmake to support CMake 3.12

### LINKED ISSUE #10427: #10330 uses non-3.12 CMake features
When I implemented https://github.com/cvc5/cvc5/pull/10330, I used:

```
SOURCE_FROM_CONTENT
```

Not realising this was new in CMake 3.25.

As such, `cvc5` fails to build with CMake 3.12, which is the documented minimum for the project.

This was reported by @BrunoDutertre here: https://github.com/cvc5/cvc5/commit/f77908cdb196f75fbc63f7c3d05ea35a1e4c7f44#commitcomment-139003709

### PR DESCRIPTION
**Pull request by aytey**
This PR fixes an issue introduced in #10330, where we use features from CMake 3.25, despite the fact we are targeting CMake 3.12 as the oldest-supported version.

Here's what the output looks like now in CMake 3.12:

```
-- Found GMP 6.2.1: /usr/lib/i386-linux-gnu/libgmp.so
VERBOSESystem version for CaDiCaL has incompatible version: required 1.6.0 but found sc2021

-- Looking for getc_unlocked
```

(the `VERBOSE` prefix is unrelated to this PR and is tracked in https://github.com/cvc5/cvc5/issues/10431).

Closes #10427

Signed-off-by: Andrew V. Teylu <andrew@tey.lu>

### CODE REVIEW

**Comment by aytey** [comment]
@BrunoDutertre could you try this? I have checked with CMake 3.12 and this now seems to work (and I confirm I got an error when using `main` with 3.12).

**Comment by BrunoDutertre** [comment]
This works for me, but you may want to take `CaDiCaL_INCLUDE_DIR` into account in `try_run`.
(Also, based on the FindGMP.cmake, maybe add support for cross-compilation).

**Comment by aytey** [comment]
> but you may want to take `CaDiCaL_INCLUDE_DIR` into account in `try_run`.
>

Ah, good point; I'll do this (shame there's no nice way to do this vs. manually setting `CMAKE_CXX_FLAGS` though).

**Comment by mpreiner** [comment]
In the GMP case we can figure out the version from its header files. This is unfortunately not the case for CaDiCaL. If we can't run CaDiCaL to get the version, we have to build it ourselves just to make sure that we have the correct version. I'm not sure if there is any other way.

**Comment by aytey** [comment]
> In the GMP case we can figure out the version from its header files. This is unfortunately not the case for CaDiCaL. If we can't run CaDiCaL to get the version, we have to build it ourselves just to make sure that we have the correct version. I'm not sure if there is any other way.

Okay, so shall I do the thing where we set `CMAKE_CXX_FLAGS` to have the include, and that's it?

**Comment by aytey** [comment]
> > > In the GMP case we can figure out the version from its header files. This is unfortunately not the case for CaDiCaL. If we can't run CaDiCaL to get the version, we have to build it ourselves just to make sure that we have the correct version. I'm not sure if there is any other way.
> > 
> > 
> > Okay, so shall I do the thing where we set `CMAKE_CXX_FLAGS` to have the include, and that's it?
> 
> Yes please!

Done!

When you're happy, I'll squash + sign-off.

**Comment by aytey** [comment]
@BrunoDutertre could you take a look at see if you're happy with how this looks? Would be good to make sure it works for you before it lands in `main`.

**Review by mpreiner — APPROVED** [review]

**Comment by aytey** [comment]
> @aytey Bruno confirmed that the fix works. Please sign-off + squash. Thanks for the fix!

Your wish is my command!

**Pull request merged**
