### PR TITLE
ci: Upgrade setup-python to v5

### PR DESCRIPTION
**Pull request by daniel-larraz**
v4 still uses node16, which is deprecated

### CODE REVIEW

**Comment by daniel-larraz** [comment]
See: 
https://github.com/cvc5/cvc5/actions/runs/7719841395
https://github.com/actions/setup-python/releases/tag/v5.0.0

**Review by netolcc06 — APPROVED** [review]
I've tested this change, but previous PR was approved before the pipeline was finished. We can go for it. Link for the CI: https://github.com/netolcc06/cvc5/actions/runs/7719007169

**Comment by daniel-larraz** [comment]
Warnings are a little bit tricky, they don't always show up. For instance, they don't show up in your link but do in your first test: https://github.com/netolcc06/cvc5/actions/runs/7717218134

**Comment by netolcc06** [comment]
> Warnings are a little bit tricky, they don't always show up. For instance, they don't show up in your link but do in your first test: https://github.com/netolcc06/cvc5/actions/runs/7717218134

For this one the setup-python change was not included. It was related to [this commit](https://github.com/netolcc06/cvc5/commit/ca7c76e3869f533624770eeb5488eaba02b692d2).

**Comment by daniel-larraz** [comment]
In fact, it was included. Notice that the warning refers to v4:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4.
```

**Comment by netolcc06** [comment]
> In fact, it was included. Notice that the warning refers to v4:
> 
> ```
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4.
> ```

I mean that the change of this version was done in [another commit](https://github.com/cvc5/cvc5/commit/582a92582c742bf48750afd45781685001b4c0a5) which triggered [this workflow](https://github.com/netolcc06/cvc5/actions/runs/7719007169). How do you want to proceed?

**Comment by daniel-larraz** [comment]
Sorry, I understand now. That makes sense. Let's just merge this PR.

**Pull request merged**
