### PR TITLE
Update set_defaults.cpp: solve-bv-as-int can lead to invalid post-assert logic string

### PR DESCRIPTION
**Pull request by nmouha**
Using solve-bv-as-int can lead to an invalid post-assert logic string

Example:
(set-logic QF_BV)
(set-option :solve-bv-as-int sum)
(set-option :output post-asserts)
(declare-const a (_ BitVec 32))
(declare-const b (_ BitVec 32))
(assert (bvule a (bvudiv #xFFFFFFFF b)))
(assert (not (= (bvurem (bvmul a b) b) #x00000000)))
(check-sat)

First line of output:
(set-logic QF_UFBVNA)

But QF_UFBVNA should be QF_UFBVNIA to avoid the following parsing error: junk ("NA") at end of logic string: QF_UFBVNA

Signed-off-by: Nicky Mouha <nicky@mouha.be>

### CODE REVIEW

**Review by yoni206 — CHANGES_REQUESTED** [review]
Thanks for this PR! Can you include, as part of it, the example that you gave as a regression test?

**Comment by nmouha** [comment]
Thank you @yoni206 ! I've added a regression test.

**Review by yoni206 — APPROVED** [review]
Thanks, this indeed seems more accurate.

**Comment by nmouha** [comment]
Thank you, @yoni206 ! Just checking if there is still something required on my side before these commits can be merged?

**Comment by yoni206** [comment]
Hi, the PR is approved, hopefully it will get merged soon. Thanks again!

**Comment by nmouha** [comment]
Great! Thank you, @yoni206 !

**Comment by nmouha** [comment]
Thank you, @mpreiner ! My commit is now squashed and signed off: https://github.com/cvc5/cvc5/pull/10796/commits/d4db755ccba2a1dc2a58669daa08228b2aab827a

**Pull request merged**
