### PR TITLE
[CMake] Improve FindGMP

### LINKED ISSUE #8792: Configure script does not find system-wide gmp library on Fedora
**Describe the bug**
The system-wide GMP library is not found by the configure script.
The library has been installed with `dnf install gmp-devel gmp-c++` and I confirm `gmp.h` and `gmpxx.h` are present in `/usr/include`, as well as the library is present in `/usr/lib64/libgmp.so`. However, the cmake script does not find it.
I've looked at your `FindGMP.cmake` file and I noticed the script tries to parse the header to extract the version of the library, looking for the `__GNU_MP_MAJOR` and similar macros. However, in the installed version of the headers this macro does not exist, so I suppose that's the reason why the `cmake` script is failing. This only happens on Fedora (and RedHat-based distros, I suppose). The library is found on Debian.

**Command line arguments**: `./configure.sh`
**cvc5 version/commit**: 6d886ae8bb345dae281b95ec152aee2106137831
**Operating system**: Fedora 36

**`configure.sh` options**  
No particular options

**`configure.sh` output**  

```
$ ./configure.sh
-- The C compiler identification is GNU 12.1.1
-- The CXX compiler identification is GNU 12.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.36.1") 
-- Building Production build
-- Performing Test HAVE_C_FLAG_O3
-- Performing Test HAVE_C_FLAG_O3 - Success
-- Configuring with C flag '-O3'
-- Performing Test HAVE_CXX_FLAG_O3
-- Performing Test HAVE_CXX_FLAG_O3 - Success
-- Configuring with CXX flag '-O3'
-- Performing Test HAVE_C_FLAG_Wall
-- Performing Test HAVE_C_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Performing Test HAVE_CXX_FLAG_Wall
-- Performing Test HAVE_CXX_FLAG_Wall - Success
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_C_FLAG_Wunused_private_field
-- Performing Test HAVE_C_FLAG_Wunused_private_field - Failed
-- Performing Test HAVE_CXX_FLAG_Wunused_private_field
-- Performing Test HAVE_CXX_FLAG_Wunused_private_field - Failed
-- Performing Test HAVE_C_FLAG_fexceptions
-- Performing Test HAVE_C_FLAG_fexceptions - Success
-- Configuring with C flag '-fexceptions'
-- Performing Test HAVE_CXX_FLAG_Wsuggest_override
-- Performing Test HAVE_CXX_FLAG_Wsuggest_override - Success
-- Configuring with CXX flag '-Wsuggest-override'
-- Performing Test HAVE_CXX_FLAG_Wnon_virtual_dtor
-- Performing Test HAVE_CXX_FLAG_Wnon_virtual_dtor - Success
-- Configuring with CXX flag '-Wnon-virtual-dtor'
-- Performing Test HAVE_C_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_C_FLAG_Wimplicit_fallthrough - Success
-- Configuring with C flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_CXX_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_CXX_FLAG_Wimplicit_fallthrough - Success
-- Configuring with CXX flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_C_FLAG_Wshadow
-- Performing Test HAVE_C_FLAG_Wshadow - Success
-- Configuring with C flag '-Wshadow'
-- Performing Test HAVE_CXX_FLAG_Wshadow
-- Performing Test HAVE_CXX_FLAG_Wshadow - Success
-- Configuring with CXX flag '-Wshadow'
-- Performing Test HAVE_CXX_FLAG_fno_extern_tls_init
-- Performing Test HAVE_CXX_FLAG_fno_extern_tls_init - Success
-- Configuring with CXX flag '-fno-extern-tls-init'
-- Performing Test HAVE_CXX_FLAG_Wclass_memaccess
-- Performing Test HAVE_CXX_FLAG_Wclass_memaccess - Success
-- Configuring with CXX flag '-Wno-class-memaccess'
-- Using GNU gold linker.
-- Disabling unit tests since assertions are disabled.
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.2", minimum required is "3") 
CMake Error at cmake/deps-helper.cmake:66 (message):
  Could not find the required dependency GMP (>= 6.1) in the system.  Please
  install it yourself or use --auto-download to let us download and build it
  for you.
Call Stack (most recent call first):
  cmake/FindGMP.cmake:48 (check_auto_download)
  CMakeLists.txt:298 (find_package)


-- Configuring incomplete, errors occurred!
See also "/cvc5/build/CMakeFiles/CMakeOutput.log".
See also "/cvc5/build/CMakeFiles/CMakeError.log".
```

### PR DESCRIPTION
**Pull request by 4tXJ7f**
Fixes #8792. This commit fixes issues with/improves our current
implementation of FindGMP:

- Version check that does not rely on regex matches in `gmp.h`. Instead,
  this commit uses a test program that checks at compile-time whether
  the GMP version is recent enough. This is more robust, because on some
  systems (such as Fedora), `gmp.h` includes another file that has that
  version information.
- It now also checks for the `gmpxx.h` header and the `gmpxx` library.
- The commit changes the compile test to use the include directories and
  libraries that were found using `find_path` and `find_library`.

### CODE REVIEW

**Comment by mudathirmahgoub** [comment]
May be this is related, but compiling for windows with `--auto-download --win64` fails in my machine missing gmpxx.h., 
whereas compiling for Linux works fine.

**Comment by 4tXJ7f** [comment]
> May be this is related, but compiling for windows with `--auto-download --win64` fails in my machine missing gmpxx.h., whereas compiling for Linux works fine.

Can you post the output of running `./configure.sh ...`? I am curious if it is mistakenly picking up the system GMP.

**Comment by mudathirmahgoub** [comment]
Here is the output in Ubuntu 20.04.4 LTS 
[make output](https://github.com/cvc5/cvc5/files/8826206/output.txt)

```bash
./configure.sh --auto-download --static --win64 --prefix=build/install
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Building Production build
-- Performing Test HAVE_C_FLAG_O3
-- Performing Test HAVE_C_FLAG_O3 - Success
-- Configuring with C flag '-O3'
-- Performing Test HAVE_CXX_FLAG_O3
-- Performing Test HAVE_CXX_FLAG_O3 - Success
-- Configuring with CXX flag '-O3'
-- Performing Test HAVE_C_FLAG_Wall
-- Performing Test HAVE_C_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Performing Test HAVE_CXX_FLAG_Wall
-- Performing Test HAVE_CXX_FLAG_Wall - Success
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_C_FLAG_Wunused_private_field
-- Performing Test HAVE_C_FLAG_Wunused_private_field - Failed
-- Performing Test HAVE_CXX_FLAG_Wunused_private_field
-- Performing Test HAVE_CXX_FLAG_Wunused_private_field - Failed
-- Performing Test HAVE_C_FLAG_fexceptions
-- Performing Test HAVE_C_FLAG_fexceptions - Success
-- Configuring with C flag '-fexceptions'
-- Performing Test HAVE_CXX_FLAG_Wsuggest_override
-- Performing Test HAVE_CXX_FLAG_Wsuggest_override - Success
-- Configuring with CXX flag '-Wsuggest-override'
-- Performing Test HAVE_CXX_FLAG_Wnon_virtual_dtor
-- Performing Test HAVE_CXX_FLAG_Wnon_virtual_dtor - Success
-- Configuring with CXX flag '-Wnon-virtual-dtor'
-- Performing Test HAVE_C_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_C_FLAG_Wimplicit_fallthrough - Success
-- Configuring with C flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_CXX_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_CXX_FLAG_Wimplicit_fallthrough - Success
-- Configuring with CXX flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_C_FLAG_Wshadow
-- Performing Test HAVE_C_FLAG_Wshadow - Success
-- Configuring with C flag '-Wshadow'
-- Performing Test HAVE_CXX_FLAG_Wshadow
-- Performing Test HAVE_CXX_FLAG_Wshadow - Success
-- Configuring with CXX flag '-Wshadow'
-- Performing Test HAVE_CXX_FLAG_fno_extern_tls_init
-- Performing Test HAVE_CXX_FLAG_fno_extern_tls_init - Success
-- Configuring with CXX flag '-fno-extern-tls-init'
-- Performing Test HAVE_CXX_FLAG_Wclass_memaccess
-- Performing Test HAVE_CXX_FLAG_Wclass_memaccess - Success
-- Configuring with CXX flag '-Wno-class-memaccess'
-- Performing Test HAVE_C_FLAG_Wno_error_unknown_pragmas
-- Performing Test HAVE_C_FLAG_Wno_error_unknown_pragmas - Success
-- Configuring with C flag '-Wno-error=unknown-pragmas'
-- Performing Test HAVE_CXX_FLAG_Wno_error_unknown_pragmas
-- Performing Test HAVE_CXX_FLAG_Wno_error_unknown_pragmas - Success
-- Configuring with CXX flag '-Wno-error=unknown-pragmas'
-- Disabling unit tests since assertions are disabled.
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Building GMP 6.2.1: /home/mudathir/Desktop/cvc5/win/build/deps/lib/libgmp.a
-- Looking for getc_unlocked
-- Looking for getc_unlocked - not found
-- Building CaDiCaL rel-1.4.1: /home/mudathir/Desktop/cvc5/win/build/deps/lib/libcadical.a
-- Building Poly 1383809f2aa5005ef20110fec84b66959518f697: /home/mudathir/Desktop/cvc5/win/build/deps/lib/libpicpoly.a, /home/mudathir/Desktop/cvc5/win/build/deps/lib/libpicpolyxx.a
-- Building SymFPU: /home/mudathir/Desktop/cvc5/win/build/deps/include/
-- Performing Test CVC5_NEED_INT64_T_OVERLOADS
-- Performing Test CVC5_NEED_INT64_T_OVERLOADS - Success
-- Performing Test CVC5_NEED_HASH_UINT64_T_OVERLOAD
-- Performing Test CVC5_NEED_HASH_UINT64_T_OVERLOAD - Failed
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for C++ include ext/stdio_filebuf.h
-- Looking for C++ include ext/stdio_filebuf.h - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Configuring with C flag '-pthread'
-- Configuring with CXX flag '-pthread'
-- Looking for ffs
-- Looking for ffs - not found
-- Looking for optreset
-- Looking for optreset - not found
-- Looking for sigaltstack
-- Looking for sigaltstack - not found
-- Looking for strerror_r
-- Looking for strerror_r - not found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for setitimer
-- Looking for setitimer - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Failed
-- Found Java: /usr/bin/java (found version "11.0.15") found components: Runtime 
-- Building ANTLR3 runtime: /home/mudathir/Desktop/cvc5/win/build/deps/lib/libantlr3c.a
-- Downloading ANTLR3 JAR: /home/mudathir/Desktop/cvc5/win/build/deps/share/java/antlr-3.4-complete.jar
-- Performing Test HAVE_CXX_FLAGWall
-- Performing Test HAVE_CXX_FLAGWall - Success
-- Performing Test HAVE_CXX_FLAGWerror
-- Performing Test HAVE_CXX_FLAGWerror - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success

cvc5 1.0.1-dev

Build profile             : production

GPL                       : off
Best configuration        : off

Assertions                : off
Debug symbols             : off
Debug context mem mgr     : off

Muzzle                    : off
Statistics                : on
Tracing                   : off

ASan                      : off
UBSan                     : off
TSan                      : off
Coverage (gcov)           : off
Profiling (gprof)         : off
Unit tests                : off
Valgrind                  : off

Shared build              : off
Python bindings           : off
Java bindings             : off
Interprocedural opt.      : off

CryptoMiniSat             : off
GLPK                      : off
Kissat                    : off
LibPoly                   : on (local)
CoCoALib                  : off
MP library                : gmp (local)
Editline                  : off

Api docs                  : off


CPPLAGS (-D...): NDEBUG CVC5_STATISTICS_ON CVC5_USE_POLY
CXXFLAGS       : -O3 -Wall -Wsuggest-override -Wnon-virtual-dtor -Wimplicit-fallthrough -Wshadow -fno-extern-tls-init -Wno-class-memaccess -Wno-error=unknown-pragmas -pthread
CFLAGS         : -O3 -Wall -fexceptions -Wimplicit-fallthrough -Wshadow -Wno-error=unknown-pragmas -pthread
Linker flags   :  -Wl,--stack,100000000 

Install prefix : /home/mudathir/Desktop/cvc5/win/build/install

cvc5 license: modified BSD

Note that this configuration is NOT built against any GPL'ed libraries, so
it is covered by the (modified) BSD license.  To build against GPL'ed
libraries which can improve cvc5's performance on arithmetic and bitvector
logics, re-configure with '-DENABLE_GPL -DENABLE_BEST'.

Now change to 'build' and type 'make', followed by 'make check' or 'make install'.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/mudathir/Desktop/cvc5/win/build
```

**Comment by 4tXJ7f** [comment]
Hmm, that looks as expected. I also just tested it in Docker and it worked fine. Can you delete the build folder and try to rebuild from scratch?

**Comment by 4tXJ7f** [comment]
Interesting... what files do you have in `/home/mudathir/Desktop/cvc5/win/build/deps/include`?

**Comment by 4tXJ7f** [comment]
So `gmpxx.h` is actually there and it seems to get the wrong include path? What is the error exactly?

**Comment by mudathirmahgoub** [comment]
> So `gmpxx.h` is actually there and it seems to get the wrong include path? What is the error exactly?

Yes, before it was missing gmpxx.h, but after I ran `sudo apt install libgmp-dev` I got this linking error.
[output.txt](https://github.com/cvc5/cvc5/files/8827996/output.txt)

**Review by mudathirmahgoub — APPROVED** [review]
LGTM

**Pull request merged**
