### PR TITLE
Use the interactive shell when piping from stdin

### PR DESCRIPTION
**Pull request by ajreynol**
Co-authored-by: Andres Noetzli <noetzli@stanford.edu>

The option `--stdin-input-per-line` makes us use the interactive shell (with outputs disabled) when piping from stdin. It is 60% slower than reading from file (whereas we 16% slower otherwise).  Thus, it is disabled by default.

The option avoids the issues on https://github.com/cvc5/cvc5/issues/8374, https://github.com/cvc5/cvc5/issues/791, https://github.com/cvc5/cvc5/issues/1862.  I am leaving those issues open since the option is not enabled by default.

### CODE REVIEW

**Comment by ajreynol** [comment]
On QF_S + QF_SLIA, I tested:
(1) reading from file,
(2) reading from stdin before this PR,
(3) reading from stdin after this PR

There were 5 benchmarks where the results differed:
```
Benchmark	“(1)"		“(2)"		“(3)"	
smtlib-2020-2/QF_SLIA/2015-Norn/HammingDistance/norn-benchmark-1049.smt2	unsat	43.238	unsat	43.4554	t/o	60.0229
smtlib-2020-2/QF_SLIA/2015-Norn/HammingDistance/norn-benchmark-1077.smt2	t/o	60.044	unsat	56.6435	t/o	60.0173
smtlib-2020-2/QF_SLIA/20180523-Reynolds/pyex/peterc-pyex-doc-cav17-zz/pymongo/pymongo-mongoclient/77b6e0c6df758aa23080cf34d64f7367c0e4c79a08ac36bc3d829dff.smt2	t/o	60.0149	t/o	60.0243	unsat	28.8842
smtlib-2020-2/QF_SLIA/2019-full_str_int/py-conbyte_cvc4/leetcode_int-add_binary/146.smt2	t/o	60.0174	t/o	60.0279	unsat	56.7673
smtlib-2020-2/QF_SLIA/2019-full_str_int/py-conbyte_cvc4/leetcode_int-restoreIpAddresses/397.smt2	t/o	60.0483	sat	55.2629	sat	54.29
```
Time on 69201 commonly solved benchmarks:
(1) : 31969.4 seconds
(2) : 32543.3 seconds
(3) : 33583.5 seconds

So currently, reading from stdin is 1.8% slower before this PR, 5.0% slower after this PR on this set. However, this is impacted by outliers where the search appears to have changed.

**Comment by 4tXJ7f** [comment]
I think that this also fixes #1862. Can you check?

**Comment by ajreynol** [comment]
Yes, it fixes that as well.

**Review by 4tXJ7f — APPROVED** [review]
LGTM. Note that we can also delete files such as `src/parser/line_buffer.{h,cpp}`, `src/parser/antlr_line_buffered_input.{h,cpp}` and related infrastructure if we use this approach. One downside that I am currently seeing (other than the performance implications): We are not going through the [`ProtfolioDriver`](https://github.com/cvc5/cvc5/blob/bc6968a19d0d0667ad80405c9f22507dea6535a3/src/main/portfolio_driver.cpp). I think that we can integrate those two in a future change, though.

**Comment by ajreynol** [comment]
A more direct test of performance, using `--parse-only` on a handful of large benchmarks shows that piping to stdin is 16% slower than reading from file before this PR, 60% slower after this PR.

**Pull request merged**
