### PR TITLE
Remove `--tear-down-incremental`

### PR DESCRIPTION
**Pull request by 4tXJ7f**
Recent experiments have shown that `--tear-down-incremental` is actually
not really helping all that much anymore and it has always been a bit of a workaround.
It is also broken on current master. This commit removes the option.

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
Results from experiments:
```
                                               status  total   solved      sat   unsat   best  timeout  memout  error  uniq  disagr  time_cpu    memory
benchmark   config                                                                                                                                     
ABVFP       2021-06-10-incremental-2               ok      4      818      801      17      3        1       0      0     0       0     130.3     364.9
            2021-06-10-incremental-tear-down-2     ok      4      818      801      17      1        1       0      0     0       0     129.2     220.2
ALIA        2021-06-10-incremental-2               ok     24   199741   190631    9110     23        1       0      0     0       0     438.4    2591.0
            2021-06-10-incremental-tear-down-2     ok     24   149103   141799    7304      1       16       0      0     0       0    2733.8    2731.0
ANIA        2021-06-10-incremental-2               ok      3    23486    22766     720      2        0       0      0     0       0      48.9     165.3
            2021-06-10-incremental-tear-down-2     ok      3    18833    18204     629      1        1       0      0     0       0     282.6     179.7
AUFNIRA     2021-06-10-incremental-2               ok    165     3080        0    3080    132       25       0      0     0       0    3245.0    3762.9
            2021-06-10-incremental-tear-down-2     ok    165     3068        0    3068     38       27       0      0     0       0    3465.0    3931.8
BV          2021-06-10-incremental-2               ok     18    35096    31804    3292     14       11       0      0     0       0    1446.9    4616.6
            2021-06-10-incremental-tear-down-2     ok     18    35614    32281    3333     10        9       0      0     0       0    1400.9    3257.5
BVFP        2021-06-10-incremental-2               ok     10     3195     2858     337     10        7       0      0     0       0     878.4    1591.7
            2021-06-10-incremental-tear-down-2     ok     10     3230     2893     337      7        7       0      0     0       0     886.2    1168.5
LIA         2021-06-10-incremental-2               ok      6    25393    21716    3677      6        0       0      0     0       0      20.1     148.5
            2021-06-10-incremental-tear-down-2     ok      6    25393    21716    3677      0        0       0      0     0       0      55.0     144.5
LRA         2021-06-10-incremental-2               ok      5    15969    15901      68      5        0       0      0     0       0      71.6     525.4
            2021-06-10-incremental-tear-down-2     ok      5    15969    15901      68      0        0       0      0     0       0     132.9     652.2
QF_ABV      2021-06-10-incremental-2               ok   1272     2597     1216    1381   1146       72       0      0     0       0   13189.1  153192.3
            2021-06-10-incremental-tear-down-2     ok   1272     2423     1219    1204    525       78       0      0     0       0   14516.8  153203.6
QF_ABVFP    2021-06-10-incremental-2               ok  18436   520902   469555   51347  18284     1742       0      0     0       0  287053.9 3029649.4
            2021-06-10-incremental-tear-down-2     ok  18436   411833   382960   28873   3046     4676       0      0     0       0  724897.3 1642777.5
QF_ALIA     2021-06-10-incremental-2               ok     44   408295   382147   26148     44        6       0      0     0       0    1247.1   10678.2
            2021-06-10-incremental-tear-down-2     ok     44   282825   269724   13101      1       30       0      0     0       0    4711.6   11015.9
QF_ANIA     2021-06-10-incremental-2               ok      5    39879    38742    1137      4        2       0      0     0       0     297.7    1419.7
            2021-06-10-incremental-tear-down-2     ok      5    40659    39272    1387      1        2       0      0     0       0     504.7     377.5
QF_AUFBV    2021-06-10-incremental-2               ok     31      509        6     503     28        7       0      0     0       0    1190.7   12937.8
            2021-06-10-incremental-tear-down-2     ok     31      239        6     233     15       19       0      0     0       0    2343.8   14869.0
QF_AUFBVLIA 2021-06-10-incremental-2               ok    441      755      386     369    382       57       0      0     0       0   11944.7  169910.6
            2021-06-10-incremental-tear-down-2     ok    441      754      385     369    128       58       0      0     0       0   12429.6  172009.4
QF_AUFBVNIA 2021-06-10-incremental-2               ok     44       60       31      29     25       15       0      0     0       0    2242.8   23135.6
            2021-06-10-incremental-tear-down-2     ok     44       60       31      29     16       15       0      0     0       0    2342.9   23380.7
QF_AUFLIA   2021-06-10-incremental-2               ok     72  1416690  1032747  383943     72       18       0      0     0       0    2647.1   20720.7
            2021-06-10-incremental-tear-down-2     ok     72   151831   101510   50321      0       26       0      0     0       0    3692.6   23433.2
QF_BV       2021-06-10-incremental-2               ok   2589    50729    44406    6323   2121      338       0      0     2       0   55994.6 2546559.4
            2021-06-10-incremental-tear-down-2     ok   2589    50009    44219    5790   1052      345       0      0     1       0   57531.3 2521706.0
QF_BVFP     2021-06-10-incremental-2               ok    584    36101    35040    1061    530       37       0      0     0       0    6805.8   47790.4
            2021-06-10-incremental-tear-down-2     ok    584    32878    31826    1052    225       58       0      0     0       0   10506.8   52953.9
QF_FP       2021-06-10-incremental-2               ok    167      711      673      38    166        0       0      0     0       0      25.3    2147.9
            2021-06-10-incremental-tear-down-2     ok    167      711      673      38     91        0       0      0     0       0      70.9    2288.6
QF_LIA      2021-06-10-incremental-2               ok     69  1883436  1434609  448827     52       57       0      0     0       0    7284.0   34076.5
            2021-06-10-incremental-tear-down-2     ok     69  1052460   826428  226032     20       61       0      0     0       0    7543.0   32420.2
QF_LRA      2021-06-10-incremental-2               to     10      388       85     303     10       10       0      0     0       0    1205.5    7240.6
            2021-06-10-incremental-tear-down-2     to     10      277       72     205      1       10       0      0     0       0    1208.0    6004.1
QF_NIA      2021-06-10-incremental-2               to     10   737304   708129   29175      8       10       0      0     0       0    1205.8    4703.6
            2021-06-10-incremental-tear-down-2     to     10   554083   525099   28984      5       10       0      0     0       0    1205.4    5472.3
QF_UF       2021-06-10-incremental-2               ok   1778    29970    25020    4950   1758       10       0      0     0       0    3060.9   44662.0
            2021-06-10-incremental-tear-down-2     ok   1778    29970    25020    4950    444       10       0      0     0       0    4842.9   50883.3
QF_UFBV     2021-06-10-incremental-2               ok   2330     5065     3322    1743   1993       21       0      0     0       0   12883.1  153777.2
            2021-06-10-incremental-tear-down-2     ok   2330     4785     3324    1461    541       27       0      0     0       0   16812.0  149936.2
QF_UFBVLIA  2021-06-10-incremental-2               ok    179      207      168      39    176        0       0      0     0       0      48.8    2455.0
            2021-06-10-incremental-tear-down-2     ok    179      207      168      39    135        0       0      0     0       0      54.2    2666.4
QF_UFFP     2021-06-10-incremental-2               ok      1        2        0       2      1        0       0      0     0       0       0.9      63.0
            2021-06-10-incremental-tear-down-2     ok      1        2        0       2      0        0       0      0     0       0       1.2      41.1
QF_UFLIA    2021-06-10-incremental-2               ok    773   305069   286548   18521    703      210       0      0     0       0   26064.4   19742.0
            2021-06-10-incremental-tear-down-2     ok    773    99876    89100   10776    538      213       0      0     0       0   26367.0   17079.8
QF_UFLRA    2021-06-10-incremental-2               ok   3058    18968    11725    7243   2883      153       0      0     3       0   32999.4  300229.2
            2021-06-10-incremental-tear-down-2     ok   3058    16308    10120    6188   1575      165       0      0     1       0   37603.1  310422.8
QF_UFNIA    2021-06-10-incremental-2               ok   1012    79662    66571   13091    999        1       0      0     0       0     996.2    7363.7
            2021-06-10-incremental-tear-down-2     ok   1012    75591    62825   12766    349        2       0      0     0       0    1766.7    8501.0
QF_UFNRA    2021-06-10-incremental-2               ok      1        6        6       0      1        0       0      0     0       0       0.0       4.5
            2021-06-10-incremental-tear-down-2     ok      1        6        6       0      0        0       0      0     0       0       0.1       4.5
UF          2021-06-10-incremental-2               ok   4067    49747     8935   40812   2130     1561       0      0     0       0  198148.8 1661173.7
            2021-06-10-incremental-tear-down-2     ok   4067    50134     8935   41199    812     1530       0      0     1       0  201057.9 1666536.3
UFLRA       2021-06-10-incremental-2               ok   1870   229693        0  229693   1112       93       0      0     0       0   30024.1   25032.6
            2021-06-10-incremental-tear-down-2     ok   1870   189015        0  189015    214      168       0      0     0       0   44936.8   29831.5
UFNIA       2021-06-10-incremental-2               ok   4063    63309     7960   55349   2405     1614       0      0     0       0  210027.3 1347027.5
            2021-06-10-incremental-tear-down-2     ok   4063    60743     7959   52784    971     1618       0      0     2       0  218072.9 1346762.2
UFNRA       2021-06-10-incremental-2               ok      4        5        0       5      3        0       0      0     0       0       0.4      18.1
            2021-06-10-incremental-tear-down-2     ok      4        5        0       5      0        0       0      0     0       0       1.5      20.8
```

**Review by nafur — APPROVED** [review]
LGTM.

**Comment by aniemetz** [comment]
Nice!

**Comment by 4tXJ7f** [comment]
After an offline discussion with @aniemetz, I am merging this. The option is broken on current master and we can still discuss it on Tuesday,

**Pull request merged**
