### PR TITLE
Remove constexprs causing build to fail on some versions of gcc/10.1.0

### PR DESCRIPTION
**Pull request by matthewsot**
These constexprs were surfacing an internal gcc bug on at least one copy of
gcc/10.1.0. This commit removes them, which causes the build to complete. It is
likely they were not necessary anyways.

Signed-off-by: Matthew Sotoudeh <sotoudeh@stanford.edu>

### CODE REVIEW

**Review by 4tXJ7f — APPROVED** [review]
LGTM

**Comment by matthewsot** [comment]
Andres found (what is probably) the relevant GCC bug here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94937

Seems to have been fixed on newer versions. I can also confirm that I can build `master` with `gcc/9.1.0`.

**Review by nafur — APPROVED** [review]
Thanks for the changes!

**Comment by matthewsot** [comment]
@4tXJ7f PTAL, I can confirm this builds as well. I also included a short description in `src/base/configuration.h`, feel free to change the wording/link/whatever. I can squash + sign whenever it seems ready.

**Review by 4tXJ7f — APPROVED** [review]
LGTM, thanks for the update!

**Comment by 4tXJ7f** [comment]
This looks great. I am just marking the PR as "do not merge" until the commit message has been updated.

**Comment by matthewsot** [comment]
On it ...

**Comment by matthewsot** [comment]
Does https://github.com/cvc5/cvc5/pull/7898/commits/ba008deee877b8eb8048af0cfe12e08890102b45 look reasonable? I noticed it pushed a bunch of other commits onto this list, perhaps my git magic didn't work as well as I thought it did (or maybe it's fine!)

**Comment by 4tXJ7f** [comment]
> Does [ba008de](https://github.com/cvc5/cvc5/commit/ba008deee877b8eb8048af0cfe12e08890102b45) look reasonable? I noticed it pushed a bunch of other commits onto this list, perhaps my git magic didn't work as well as I thought it did (or maybe it's fine!)

Yep, that works. Thanks again for the updates. I've squashed and merged the commit with the new commit message.

**Pull request merged**
