### PR TITLE
Properly cache assertions in static learning preprocessing pass.

### PR DESCRIPTION
**Pull request by mpreiner**
The cache is user-context dependent and guarantees that `ppStaticLearn` is only called once per assertion in a given context - if assertions are popped from the context and added again `ppStaticLearn` is called again on that assertion. Further, the preprocessing pass now also handles the splitting of top-level AND terms. Before that each theory was responsible for splitting and caching. Refactoring the corresponding `ppStaticLearn` theory methods will be part of future PRs.

Marking do-not-merge until cluster runs finished.

### CODE REVIEW

**Comment by mpreiner** [comment]
diff on non-incremental SMT-LIB with 300s timeout:
```
             status  total  solved  sat  unsat  best  timeout  memout  error  uniq  disagr  time_cpu  memory
config                                                                                                      
run-cache/       ok     73      39    9     30    39       34       0      0    39       0   19344.8 32864.1
run-nocache/     ok     73      34   17     17    34       39       0      0    34       0   21356.4 33354.3
```

```
                       status  total  solved  sat  unsat  best  timeout  memout  error  uniq  disagr  time_cpu  memory
benchmark config                                                                                                      
AUFBV     run-cache/       to      1       0    0      0     0        1       0      0     0       0     300.4  1140.0
          run-nocache/     ok      1       1    0      1     1        0       0      0     1       0     282.1  1142.4
AUFNIRA   run-cache/       ok      1       1    0      1     1        0       0      0     1       0      60.4    43.4
          run-nocache/     to      1       0    0      0     0        1       0      0     0       0     300.3   128.4
FP        run-cache/       to      1       0    0      0     0        1       0      0     0       0     300.3   218.1
          run-nocache/     ok      1       1    1      0     1        0       0      0     1       0     294.7   206.1
LRA       run-cache/       ok      1       1    0      1     1        0       0      0     1       0     290.5    88.8
          run-nocache/     to      1       0    0      0     0        1       0      0     0       0     300.3    89.2
QF_ABV    run-cache/       ok      2       2    2      0     2        0       0      0     2       0     595.6   507.9
          run-nocache/     to      2       0    0      0     0        2       0      0     0       0     600.6   504.1
QF_ABVFP  run-cache/       to      1       0    0      0     0        1       0      0     0       0     300.3    88.8
          run-nocache/     ok      1       1    0      1     1        0       0      0     1       0     284.4   279.3
QF_BV     run-cache/       ok      8       6    1      5     6        2       0      0     6       0    2365.2  3557.9
          run-nocache/     ok      8       2    2      0     2        6       0      0     2       0    2391.4  3576.2
QF_DT     run-cache/       ok      2       1    0      1     1        1       0      0     1       0     594.3   297.8
          run-nocache/     ok      2       1    1      0     1        1       0      0     1       0     600.2   295.1
QF_FP     run-cache/       to      1       0    0      0     0        1       0      0     0       0     300.3   743.9
          run-nocache/     ok      1       1    0      1     1        0       0      0     1       0     280.9   751.9
QF_IDL    run-cache/       ok      6       1    1      0     1        5       0      0     1       0    1797.0   758.0
          run-nocache/     ok      6       5    3      2     5        1       0      0     5       0    1757.2   756.1
QF_LIA    run-cache/       ok      5       3    2      1     3        2       0      0     3       0    1487.0  1098.5
          run-nocache/     ok      5       2    2      0     2        3       0      0     2       0    1492.8  1097.3
QF_LRA    run-cache/       ok      1       1    0      1     1        0       0      0     1       0     296.8   265.3
          run-nocache/     to      1       0    0      0     0        1       0      0     0       0     300.3   261.2
QF_NIA    run-cache/       ok      9       4    3      1     4        5       0      0     4       0    2695.2  1265.0
          run-nocache/     ok      9       5    2      3     5        4       0      0     5       0    2661.5  1258.5
QF_NRA    run-cache/       to      5       0    0      0     0        5       0      0     0       0    1501.6  2783.1
          run-nocache/     ok      5       5    2      3     5        0       0      0     5       0    1481.0  2782.2
QF_SLIA   run-cache/       to      4       0    0      0     0        4       0      0     0       0    1201.2   499.9
          run-nocache/     ok      4       4    4      0     4        0       0      0     4       0    1156.5   516.8
QF_UF     run-cache/       ok     10       9    0      9     9        1       0      0     9       0     895.3   408.0
          run-nocache/     ok     10       1    0      1     1        9       0      0     1       0    2988.6   887.1
QF_UFBV   run-cache/       to      1       0    0      0     0        1       0      0     0       0     300.3   662.6
          run-nocache/     ok      1       1    0      1     1        0       0      0     1       0     299.5   663.8
QF_UFIDL  run-cache/       ok      2       2    0      2     2        0       0      0     2       0     577.0   245.7
          run-nocache/     to      2       0    0      0     0        2       0      0     0       0     600.6   250.6
UFLIA     run-cache/       to      1       0    0      0     0        1       0      0     0       0     300.3    87.8
          run-nocache/     ok      1       1    0      1     1        0       0      0     1       0      25.5    32.1
UFNIA     run-cache/       ok     11       8    0      8     8        3       0      0     8       0    3185.8 18103.6
          run-nocache/     ok     11       3    0      3     3        8       0      0     3       0    3258.0 17875.9
```
incremental still running.

**Comment by mpreiner** [comment]
diff on incremental SMT-LIB with 600s timeout:
```
                status  total   solved      sat    unsat  best  timeout  memout  error  uniq  disagr  time_cpu   memory
config                                                                                                                 
run-inc-nocache     ok    184  8228843  6936719  1292124   140      178       1      0     2       0  110276.8 153970.3
run-inc-cache       ok    184  8134922  6869255  1265667   121      181       1      0     0       0  110329.7 154494.8
```

```
                          status  total   solved      sat   unsat  best  timeout  memout  error  uniq  disagr  time_cpu  memory
benchmark config                                                                                                               
BV        run-inc-cache       to      1      440      376      64     1        1       0      0     0       0     600.0   478.4
          run-inc-nocache     to      1      435      373      62     1        1       0      0     0       0     600.0   477.4
QF_ABV    run-inc-cache       to      3      148        0     148     2        3       0      0     0       0    1800.2  1091.5
          run-inc-nocache     to      3      149        0     149     3        3       0      0     0       0    1800.3  1098.4
QF_ABVFP  run-inc-cache       ok     38     2571     2198     373    32       37       0      0     0       0   22797.7 42629.8
          run-inc-nocache     ok     38     2533     2178     355    27       37       0      0     0       0   22773.1 42320.6
QF_AUFBV  run-inc-cache       to      2       22        0      22     2        2       0      0     0       0    1200.1   969.7
          run-inc-nocache     to      2       22        0      22     1        2       0      0     0       0    1200.0   988.9
QF_AUFLIA run-inc-cache       to     14  2745581  2446637  298944     6       14       0      0     0       0    8407.7 18635.4
          run-inc-nocache     ok     14  2766076  2469968  296108    11       13       0      0     0       0    8399.9 18628.3
QF_BV     run-inc-cache       ok      9      442      193     249     3        8       1      0     0       0    5305.1 27772.6
          run-inc-nocache     ok      9      446      198     248     9        6       1      0     2       0    5276.5 28033.1
QF_LIA    run-inc-cache       to     25  4059796  3157533  902263    12       25       0      0     0       0   15014.3 26946.4
          run-inc-nocache     to     25  4111972  3180502  931470    14       25       0      0     0       0   15012.1 26149.3
QF_LRA    run-inc-cache       to      2      103       18      85     1        2       0      0     0       0    1201.4  2320.5
          run-inc-nocache     to      2      104       19      85     1        2       0      0     0       0    1201.4  2362.7
QF_NIA    run-inc-cache       to     10   613470   585305   28165     3       10       0      0     0       0    6006.9  4667.8
          run-inc-nocache     to     10   635980   607511   28469     9       10       0      0     0       0    6008.0  4675.4
QF_UFBV   run-inc-cache       to      3      259        0     259     1        3       0      0     0       0    1800.8 14501.3
          run-inc-nocache     to      3      263        0     263     3        3       0      0     0       0    1800.8 14698.3
QF_UFLIA  run-inc-cache       to     49   661714   636882   24832    33       49       0      0     0       0   29403.7  7161.4
          run-inc-nocache     to     49   661031   636275   24756    44       49       0      0     0       0   29404.5  7226.9
QF_UFLRA  run-inc-cache       ok      4       49       49       0     3        3       0      0     0       0    2390.9  5938.7
          run-inc-nocache     ok      4       49       49       0     3        3       0      0     0       0    2399.0  5942.5
QF_UFNIA  run-inc-cache       to      1    45169    40064    5105     1        1       0      0     0       0     600.0   185.8
          run-inc-nocache     to      1    44715    39646    5069     1        1       0      0     0       0     600.0   187.3
UF        run-inc-cache       to      1        2        0       2     1        1       0      0     0       0     600.1    42.1
          run-inc-nocache     to      1        0        0       0     0        1       0      0     0       0     600.1    40.5
UFLRA     run-inc-cache       to     17     3640        0    3640    17       17       0      0     0       0   10200.5   602.8
          run-inc-nocache     to     17     3555        0    3555     9       17       0      0     0       0   10200.7   601.1
UFNIA     run-inc-cache       to      5     1516        0    1516     3        5       0      0     0       0    3000.3   550.6
          run-inc-nocache     to      5     1513        0    1513     4        5       0      0     0       0    3000.4   539.6

```

**Comment by ajreynol** [comment]
I'm a bit uneasy about this PR. It adds an extra cached value for all subterms of the input, even for cases where no theories use static learning.

I think we should actually revisit disabling this preprocessing pass entirely for arithmetic, as it appears to only be motivated by some very specific heuristics for ITEs.

A further thing to note is that this entire preprocessing pass I'd like to eventually consolidate into the "learned rewrite" pass: https://github.com/cvc5/cvc5/blob/master/src/preprocessing/passes/learned_rewrite.h.

For now, to make progress, I suppose that since the results look ok, we can merge.  In the meantime, can you also try a run with `--no-static-learning`?

**Comment by mpreiner** [comment]
Just to clarify: It does not add cached values for all subterms of the input. It does only adds input assertions to the cache + children of top-level AND nodes.

**Comment by ajreynol** [comment]
Ah, cool, good to know.  I think this looks fine to me.  I would still be interested in revisiting this entire preprocessing pass, in particular, whether we should use it for arithmetic.

**Review by ajreynol — APPROVED** [review]

**Pull request merged**
