### PR TITLE
Add Result.java to the java API

### PR DESCRIPTION
**Pull request by mudathirmahgoub**
This PR adds Result.java ResultTest.java and cvc5_Result.cpp to the java api.

### CODE REVIEW

**Comment by mudathirmahgoub** [comment]
This PR depends on (#6196).
To make the PR small, the files are not included yet in the build. They are included in this [branch](https://github.com/mudathirmahgoub/CVC4/tree/sort)

**Review by 4tXJ7f — CHANGES_REQUESTED** [review]
Missing boilerplate in all files but otherwise it LGTM.

**Comment by mudathirmahgoub** [comment]
> Missing boilerplate in all files but otherwise it LGTM.

Added comments from the main branch.

**Review by 4tXJ7f — APPROVED** [review]
LGTM

**Pull request merged**
