### PR TITLE
Refactor abs rewriting

### PR DESCRIPTION
**Pull request by nafur**
This PR refactors rewriting for `ABS` to also support real algebraic number. We also generalize the `ABS` operator to real arguments in general, instead of integer arguments.

### CODE REVIEW

**Comment by ajreynol** [comment]
Don't we allow ABS for real as well?

**Comment by nafur** [comment]
> Don't we allow ABS for real as well?

No, the type rule requires integers.

**Comment by nafur** [comment]
> Hm I'm surprised by this, shouldn't we support ABS for real?

I'd argue that we should, in particular as we only need to remove the assertion: the code already uses `mkConstRealOrInt` properly, I think. One general question about `ABS`, though: is there **any** solving technique for this?

**Comment by ajreynol** [comment]
ABS is just syntax sugar, it should just be eliminated during preprocessing/rewriting.

**Comment by nafur** [comment]
> ABS is just syntax sugar, it should just be eliminated during preprocessing/rewriting.

The rewriter should now support ABS for both integer and real, rational and RAN numbers.

**Review by ajreynol — APPROVED** [review]

**Pull request merged**
