### PR TITLE
Replace `Debug` by `Trace`

### PR DESCRIPTION
**Pull request by nafur**
This PR replaces all usages of `Debug()` by `Trace()`, the same for similar methods like `Debug.isOn()`.
Given that `Debug` is no longer used then, it is removed.

### CODE REVIEW

**Review by HanielB — COMMENTED** [review]
Did you evaluate the performance impact? I did this once and evaluated and the difference seemed bigger than noise.

**Comment by mpreiner** [comment]
Should we prefix all Debug tags with `dbg::`, `dbg-` or `dbg:`?

**Comment by mpreiner** [comment]
> Did you evaluate the performance impact? I did this once and evaluated and the difference seemed bigger than noise.

How did you evaluate this before, a production build with tracing enabled?

**Comment by nafur** [comment]
> > Did you evaluate the performance impact? I did this once and evaluated and the difference seemed bigger than noise.
> 
> How did you evaluate this before, a production build with tracing enabled?

@ajreynol mentioned this as well. I'll run some benchmarks with production+tracing.

**Comment by nafur** [comment]
So I've run 100 random benchmarks from every (non-incremental) logic.
```
$ cmpr.py --show-diff -G slurmwd/12101057-cvc5-*
                               status  total  solved  sat  unsat  best  timeout  memout  error  uniq  disagr  time_cpu  memory
benchmark config                                                                                                              
AUFBV     12101057-cvc5-master     ok      1       1    0      1     1        0       0      0     1       0     273.5   513.8
          12101057-cvc5-pr         to      1       0    0      0     0        1       0      0     0       0     300.3   512.3
LIA       12101057-cvc5-master     to      1       0    0      0     0        1       0      0     0       0     300.3    42.8
          12101057-cvc5-pr         ok      1       1    0      1     1        0       0      0     1       0       0.5     4.8
NIA       12101057-cvc5-master     to      1       0    0      0     0        1       0      0     0       0     300.3   108.0
          12101057-cvc5-pr         ok      1       1    1      0     1        0       0      0     1       0     187.9    79.8
QF_ALIA   12101057-cvc5-master     ok      1       1    1      0     1        0       0      0     1       0     249.0   206.0
          12101057-cvc5-pr         to      1       0    0      0     0        1       0      0     0       0     300.3   186.6
QF_ANIA   12101057-cvc5-master     ok      1       1    1      0     1        0       0      0     1       0     263.1   117.8
          12101057-cvc5-pr         to      1       0    0      0     0        1       0      0     0       0     300.3    72.9
QF_IDL    12101057-cvc5-master     ok      8       8    6      2     8        0       0      0     8       0     868.8  3941.9
          12101057-cvc5-pr         to      8       0    0      0     0        8       0      0     0       0    2402.7  3257.7
QF_LIA    12101057-cvc5-master     ok      4       4    2      2     4        0       0      0     4       0     617.3  1009.1
          12101057-cvc5-pr         to      4       0    0      0     0        4       0      0     0       0    1201.2   718.3
QF_LRA    12101057-cvc5-master     ok      4       4    3      1     4        0       0      0     4       0     580.4   917.0
          12101057-cvc5-pr         to      4       0    0      0     0        4       0      0     0       0    1201.2   856.7
QF_NIA    12101057-cvc5-master     ok     18      13    7      6    13        0       0      0    13       0    1423.3  1145.3
          12101057-cvc5-pr         ok     18       5    5      0     5        9       0      0     5       0    3650.3   912.4
QF_RDL    12101057-cvc5-master     ok      2       2    1      1     2        0       0      0     2       0     520.3   315.6
          12101057-cvc5-pr         to      2       0    0      0     0        2       0      0     0       0     600.6   310.4
QF_UFBV   12101057-cvc5-master     to      1       0    0      0     0        1       0      0     0       0     300.4   817.1
          12101057-cvc5-pr         ok      1       1    0      1     1        0       0      0     1       0     287.6   820.3
QF_UFIDL  12101057-cvc5-master     ok      4       4    0      4     4        0       0      0     4       0     953.6   374.5
          12101057-cvc5-pr         to      4       0    0      0     0        4       0      0     0       0    1201.2   363.9
QF_UFLIA  12101057-cvc5-master     ok      1       1    0      1     1        0       0      0     1       0     249.3    54.9
          12101057-cvc5-pr         to      1       0    0      0     0        1       0      0     0       0     300.3    48.6
QF_UFNIA  12101057-cvc5-master     ok      3       3    3      0     3        0       0      0     3       0       3.7    23.0
          12101057-cvc5-pr         ok      3       0    0      0     0        0       0      0     0       0       4.6    23.4
```
Nontrivial benchmarks (>=1s) which slowed down significantly (>= 2x)
```
$ cmpr.py --vbs -q "time_cpu>=1" -q "slowdown>=2" -G slurmwd/12101057-cvc5-* | grep -v "virtual best"
                               status  total  solved  sat  unsat  best  timeout  memout  error  uniq  disagr  time_cpu  memory
benchmark config                                                                                                              
LIA       12101057-cvc5-master     to      1       0    0      0     0        1       0      0     0       0     300.3    42.8
          12101057-cvc5-pr         ok      1       1    0      1     1        0       0      0     1       0       0.5     4.8
NIA       12101057-cvc5-master     ok      1       1    0      1     1        0       0      0     0       0      46.1    34.6
          12101057-cvc5-pr         ok      1       1    0      1     0        0       0      0     0       0     286.6    52.7
QF_ANIA   12101057-cvc5-master     ok      5       5    3      2     4        0       0      0     0       0     198.9   246.6
          12101057-cvc5-pr         ok      5       5    3      2     1        0       0      0     0       0     381.7   249.7
QF_AUFNIA 12101057-cvc5-master     ok      4       4    3      1     4        0       0      0     0       0      17.8   104.5
          12101057-cvc5-pr         ok      4       4    3      1     0        0       0      0     0       0     592.8   232.9
QF_IDL    12101057-cvc5-master     ok     22      22   18      4    22        0       0      0     6       0     456.0  4526.0
          12101057-cvc5-pr         ok     22      16   13      3     0        6       0      0     0       0    2583.2  4103.3
QF_LIA    12101057-cvc5-master     ok      7       7    6      1     7        0       0      0     2       0     174.1   519.2
          12101057-cvc5-pr         ok      7       5    5      0     0        2       0      0     0       0     666.3   434.9
QF_LIRA   12101057-cvc5-master     ok      3       3    1      2     3        0       0      0     0       0      28.1   166.7
          12101057-cvc5-pr         ok      3       3    1      2     0        0       0      0     0       0     106.4   167.7
QF_LRA    12101057-cvc5-master     ok      3       3    2      1     3        0       0      0     3       0     362.2   702.0
          12101057-cvc5-pr         to      3       0    0      0     0        3       0      0     0       0     900.9   664.2
QF_NIA    12101057-cvc5-master     ok     43      25   17      8    25        4       0      0    11       0    2283.1  1734.7
          12101057-cvc5-pr         ok     43      15   12      3     1       11       0      0     1       0    5023.8  1583.8
QF_NRA    12101057-cvc5-master     ok      3       3    3      0     3        0       0      0     0       0      89.3   326.3
          12101057-cvc5-pr         ok      3       3    3      0     0        0       0      0     0       0     195.1   325.2
QF_RDL    12101057-cvc5-master     ok      1       1    1      0     1        0       0      0     0       0      41.6   276.1
          12101057-cvc5-pr         ok      1       1    1      0     0        0       0      0     0       0     159.6   278.8
QF_S      12101057-cvc5-master     ok      2       2    2      0     2        0       0      0     0       0       3.2    20.9
          12101057-cvc5-pr         ok      2       2    2      0     0        0       0      0     0       0       6.9    20.8
QF_SLIA   12101057-cvc5-master     ok      2       2    0      2     2        0       0      0     0       0       9.5    51.1
          12101057-cvc5-pr         ok      2       2    0      2     0        0       0      0     0       0      21.2    49.4
QF_UFIDL  12101057-cvc5-master     ok      1       1    0      1     1        0       0      0     0       0       0.8     9.3
          12101057-cvc5-pr         ok      1       1    0      1     0        0       0      0     0       0       1.6     9.3
QF_UFNIA  12101057-cvc5-master     ok      4       2    2      0     2        1       0      0     1       0     375.1    93.7
          12101057-cvc5-pr         ok      4       1    1      0     0        1       0      0     0       0     305.7   139.0
UF        12101057-cvc5-master     ok      1       1    0      1     1        0       0      0     0       0       7.7    58.2
          12101057-cvc5-pr         ok      1       1    0      1     0        0       0      0     0       0      16.7    60.2
UFNIA     12101057-cvc5-master     ok      3       2    0      2     2        0       0      0     0       0      75.9   129.7
          12101057-cvc5-pr         ok      3       2    0      2     0        1       0      0     0       0     443.2   180.2
```

**Comment by nafur** [comment]
Note that a certain slowdown is to be expected here, and the integer reasoning seems to be rather unstable (probably due to node ids changing). I'd argue this is acceptable...

**Comment by HanielB** [comment]
I'd say it's fine as well, given that this only affects tracing builds, right?

**Comment by ajreynol** [comment]
Gereon and I are discussing offline, this PR would increase runtime on trace-enabled builds by roughly 40%, which I do not find to be acceptable.

**Comment by ajreynol** [comment]
The solution here is likely to correct performance issues in the current `Debug` traces.  It seems from the numbers to suggest that `Debug` in the (linear) arithmetic solver may be to blame.  It might be worthwhile at this point investigating this further.

**Comment by ajreynol** [comment]
Another suggestion is to simply remove low-level `Debug` e.g. from src/context/ and some places in the core `Node` utilities.  I don't think anyone uses these.

**Comment by HanielB** [comment]
I used it two weeks ago. :)

**Comment by nafur** [comment]
With these changes (on 200 random benchmarks per logic) we have no significant outliers anymore and the general picture is this:
```
$ ./analyze.sh --show-common -t slurmwd/121510*
                             status  total  solved   sat  unsat  best  timeout  memout  error  uniq  disagr  time_cpu   memory
config                                                                                                                        
12151018-cvc5-master             ok   7763    7763  2842   4921  6510        0       0      0     0       0   10640.8 133658.2
12151049-cvc5-pr                 ok   7763    7763  2842   4921  6454        0       0      0     0       0   10641.5 133694.2
12151018-cvc5-master-tracing     ok   7763    7763  2842   4921  5577        0       0      0     0       0   11329.8 134539.9
12151049-cvc5-pr-tracing         ok   7763    7763  2842   4921  5322        0       0      0     0       0   12420.9 134354.9
```
so the average slowdown from enabling tracing goes up from 6.5% to 16.7%.

**Comment by nafur** [comment]
I've rerun these experiments, we now have 10-11% slowdown, compared to 4-5% on master. I think we should merge.

**Review by ajreynol — APPROVED** [review]
I'm in favor of this change now, based on the overhead.  

I'm approving, although as a comment I would prefer eliminating some of the statements modified in this PR, e.g. more of those in `context/` and `Debug("gc")`.

**Review by 4tXJ7f — APPROVED** [review]
LGTM. If we plan on making additional changes to `Trace()` statements, I'd be in favor of moving those to a future PR (the PR is big enough as it is).

**Pull request merged**
