### PR TITLE
Add `-o unsat-core-lemmas-benchmark`

### PR DESCRIPTION
**Pull request by ajreynol**
Can be used to determine which lemmas may have been the source of an unsoundness.

In particular, with `-o unsat-core-lemmas-benchmark`, the benchmark can be rerun manually and further delta debugged.

### CODE REVIEW

**Comment by ajreynol** [comment]
CI is failing due to the way proofs are managed when connecting to CNF, this is fixed here: https://github.com/cvc5/cvc5/pull/10324.

Review that PR first.

**Comment by HanielB** [comment]
Can you make the message in the PR more clear? What do you mean by source of unsoundness?

**Comment by ajreynol** [comment]
Marking "major" since this feature is mentioned in the forthcoming blog post.

**Review by HanielB — APPROVED** [review]
LGTM

**Pull request merged**
