### PR TITLE
ci: Upgrade actions

### PR DESCRIPTION
**Pull request by netolcc06**
Upgrade checkout, cache and upload-artifact actions versions.

### CODE REVIEW

**Review by daniel-larraz — CHANGES_REQUESTED** [review]
Action actions/setup-python@v2 in .github/workflows/package_pypi.yml and 
action actions/github-script@v6.4.0 in .github/workflows/docs_upload.yml also trigger warnings.

**Review by mpreiner — APPROVED** [review]
LGTM

**Comment by mpreiner** [comment]
Oh just saw @daniel-larraz comment, let's update the remaining actions too.

**Comment by netolcc06** [comment]
@daniel-larraz can you point me to these warnings? I thought they would be located at the [bottom of this page](https://github.com/cvc5/cvc5/actions/runs/7715295282) together with the artifacts.

**Comment by daniel-larraz** [comment]
> @daniel-larraz can you point me to these warnings? I thought they would be located at the [bottom of this page](https://github.com/cvc5/cvc5/actions/runs/7715295282) together with the artifacts.

@netolcc06  That page only shows the warnings triggered in the **CI** workflow.

You can find the warnings triggered in the other workflows here:
https://github.com/cvc5/cvc5/actions/runs/7704921386
https://github.com/cvc5/cvc5/actions/runs/7715567807

The docs_upload workflow also shows an error but it looks an orthogonal issue, so it should be addressed separately.

**Review by daniel-larraz — APPROVED** [review]
LGTM now.

**Pull request merged**
