### PR TITLE
Restricting the bit-width in int-to-bv

### PR DESCRIPTION
**Pull request by yoni206**
`cvc5` only supports bit-widths of `unsigned` size for BitVector sorts (see, e.g., [here](https://github.com/cvc5/cvc5/blob/4338d9d49a41022d34cd4cbabf17a66fdf39efae/src/expr/node_manager_template.cpp#L178)). 

This PR checks that the provided bit-width for the `int-to-bv` option is in the right range.

Fixes https://github.com/cvc5/cvc5-projects/issues/425 and includes a regression that is based on the test from the issue.

### CODE REVIEW

**Review by ajreynol — CHANGES_REQUESTED** [review]
Can the maximum be specified in the options toml?  E.g. https://github.com/cvc5/cvc5/blob/main/src/options/proof_options.toml#L42

**Comment by yoni206** [comment]
done [b1800f4](https://github.com/cvc5/cvc5/pull/8814/commits/b1800f4ca3c16cb03aa2a1ab3ecf9f3c555c5a36) .

**Review by ajreynol — APPROVED** [review]

**Comment by yoni206** [comment]
@4tXJ7f I've disabled the dumping test for the new regression. Dumping assumes that the return status would be 0. But here the `OptionException` is thrown early, and so the return status is `1`.

**Review by 4tXJ7f — APPROVED** [review]
LGTM. We often disable the dump tester for regressions that expect parsing errors.

**Pull request merged**
