### PR TITLE
Fix out-of-bounds vector accesses

### PR DESCRIPTION
**Pull request by jamesjer**
I am about to build cvc5 for the Fedora Linux distribution.  I ran the tests first, and many failed.  The reason is that the Fedora project builds with `-D_GLIBCXX_ASSERTIONS`.  Failing C++ assertions caused the test failures.  The assertions all failed for the same reason: out of bounds vector accesses.

In the `trigger_database.cpp` case, when a node is removed from `trNodes`, the index variable `i` is properly decremented so the loop doesn't skip an element.  However, the vector is now one smaller.  Since `tsize` is not decremented, the loop walks off the end of the vector.

Twice in `eq_proof.cpp`, a vector named `premises` is cleared, but then elements of the vector are accessed.  After the `clear` operation, there are 0 elements in the vector.  The intent seems to have been to erase all but one element of the vector.  I have changed the code to stash the element to keep in a local variable, clear the vector, then put that one element back in the vector.  After doing so, the only valid vector index is zero.

With this change, all of the tests pass.

I highly recommend that you build with `-D_GLIBCXX_ASSERTIONS` to catch errors like this.

### CODE REVIEW

**Review by ajreynol — APPROVED** [review]
LGTM, thanks a lot for the fixes.

**Comment by mpreiner** [comment]
@jamesjer Thanks for the fix! Can you sign off your commit according to our [contribution guidelines](https://github.com/cvc5/cvc5/blob/main/CONTRIBUTING.md).

**Comment by jamesjer** [comment]
Of course, sorry to have forgotten that.

**Comment by mpreiner** [comment]
> Of course, sorry to have forgotten that.

No worries and thanks a lot!

**Pull request merged**
