### PR TITLE
Rename TO_FP operator kinds.

### PR DESCRIPTION
**Pull request by aniemetz**
FLOATINGPOINT_TO_FP_FP -> FLOATINGPOINT_TO_FP_FROM_FP
FLOATINGPOINT_TO_FP_IEEE_BITVECTOR -> FLOATINGPOINT_TO_FP_FROM_IEEE_BV
FLOATINGPOINT_TO_FP_SIGNED_BITVECTOR -> FLOATINGPOINT_TO_FP_FROM_SBV
FLOATINGPOINT_TO_FP_UNSIGNED_BITVECTOR -> FLOATINGPOINT_TO_FP_FROM_UBV
FLOATINGPOINT_TO_FP_REAL -> FLOATINGPOINT_TO_FP_FROM_REAL

### CODE REVIEW

**Comment by ajreynol** [comment]
I'm wondering if we should remove the `TO_FP_` from these names.

For a point of reference, there is `STRING_FROM_INT` here: https://github.com/cvc5/cvc5/blob/master/src/api/cpp/cvc5_kind.h#L2917

I think that SMT-LIB is actual inconsistent here, where `to_fp` is used whereas in strings there is `str.from_int`.  I guess it is a question of whether to match SMT-LIB syntax or to be internally consistent.

**Comment by aniemetz** [comment]
I would like to keep `TO_FP` for the reason that this is the name of the operator in SMT-LIB. Note that we also have the `FLOATINGPOINT_TO_FP_GENERIC` operator, which would be rather disconnected if we drop `TO_FP`.

**Comment by martin-cs** [comment]
@ajreynol There is a reason for the inconsistency.  It is that there are two conventions, the older one of just naming things and the newer one of `fp.whatever`.  The fp operators follow the newer convention while some of the conversions follow the older one.  I believe this is one of the things that @tinelli et al. plan to fix in SMT-LIB3.

**Review by martin-cs — APPROVED** [review]
Looks good!

**Pull request merged**
