### PR TITLE
Preliminary draft of changes for SMT comp 2021 for quantifiers

### PR DESCRIPTION
**Pull request by ajreynol**
Covers improvements to quantifiers.

### CODE REVIEW

**Review by 4tXJ7f — APPROVED** [review]
LGTM

**Comment by ajreynol** [comment]
One issue: I've added 2 logics with FP to the "main" quantifiers block, which is the right place for them.  However, this doesnt enable `--fp-exp`.

Looking at the script, it looks like we always want `--fp-exp` enabled.  Perhaps we even want `--fp-exp` enabled by default in general at this point, as it would also simplify our testing.  What do you think @aniemetz ?

**Comment by martin-cs** [comment]
( Not @aniemetz but `--fp-ext` will crash on some formats.  I not currently aware of any correctness issues but ... that could well be because I haven't looked hard enough. )

**Comment by aniemetz** [comment]
Yes, what @martin-cs said.

**Comment by aniemetz** [comment]
@ajreynol we should enable it in the SMT-COMP script for all configurations.

**Pull request merged**
