### PR TITLE
Fix policy for rewriting string equalities

### LINKED ISSUE #6101: Solution soundness bug in string logic
commit: 4c6e0a73

```
$ cvc4 -q --strings-exp --produce-models --check-models bug.smt2
Fatal failure within void CVC4::smt::CheckModels::checkModel(CVC4::smt::Model*, CVC4::context::CDList<CVC4::NodeTemplate<true> >*, bool) 
at CVC4/src/smt/check_models.cpp:131
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (let ((_let_1 (str.replace x "A" "B"))) (let ((_let_2 (not (not (= (= "A" _let_1) false))))) 
(= (= x (str.replace x (str.replace "B" (str.replace x _let_1 "B") "B") "B")) (not (= _let_2 _let_2)))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
$ cvc4-1.8 -q --strings-exp --produce-models --check-models bug.smt2
unsat
$ z3release bug.smt2
unsat
$ cat bug.smt2
(declare-fun x () String)
(declare-fun y () String)
(declare-fun z () Int)
(assert (= (= x (str.replace x (str.replace "B" (str.replace x (str.replace x "A" "B") "B") "B") "B")) (not (= 
(not (not (= (= "A" (str.replace x "A" "B")) false))) (not (not (= (= "A" (str.replace x "A" "B")) false)))))))
(check-sat)
```

### LINKED ISSUE #6913: Solution soundness issue on string formula
Commit: https://github.com/cvc5/cvc5/commit/b251476af6095e600e227b659c06fb3393e82af5
OS: Ubuntu 18.04

```
[517] % cvc4-1.8 --strings-exp -q small.smt2
unsat
[518] % z3release small.smt2
unsat
[519] % cvc5 --strings-exp -q small.smt2
sat
[520] % cvc5 --strings-exp --check-models -q small.smt2
Fatal failure within void cvc5::smt::CheckModels::checkModel(cvc5::smt::Model*, cvc5::context::CDList<cvc5::NodeTemplate<true> >*, bool) at /local/suz-local/software/CVC4/src/smt/check_models.cpp:125
Internal error detected SmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (let ((_let_1 (str.len a))) (= (str.++ a "0" (str.at (str.substr (str.++ a a a) 0 3) _let_1) "A") (str.++ "0" (str.from_code _let_1) (str.replace "AA" (str.++ a "AA") a))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
[521] % 
[521] % cat small.smt2
(declare-fun a () String)
(assert
 (= (str.++ a "0" (str.at (str.substr (str.++ a a a) 0 3) (str.len a)) "A")
  (str.++ "0" (str.from_code (str.len a)) (str.replace "AA" (str.++ a "AA") a))))
(check-sat)
[522] % 
```

### PR DESCRIPTION
**Pull request by ajreynol**
This PR simplifies our rewriter for string equalities. We do not try to rewrite equalities to true/false by default.

This prevents cases where lemmas may contain vacuous premises that rewrite to false, hence making a lemma rewrite to true.

This PR reorganizes the interplay between the rewrite and the post-processing of rewrites via extended equality rewriting.

Fixes #6913.  Also adds benchmarks from #6101 which appear related but were fixed in previous commits, thus fixes #6101 as well.

### CODE REVIEW

**Comment by ajreynol** [comment]
Results on SMT-LIB QF_S + QF_SLIA, 60 sec timeout:
```
                           Configuration  #unsat      time    #sat      time #solved    #total
                         CVC5-072521-4_d   26329    4576.9   41401     31542     67730     69903
                       cvc5-072721-fsr_d   26311   4340.37   41429   31887.9     67740     69903



For unsatisfiable : 
                         CVC5-072521-4_d       X      29
                       cvc5-072721-fsr_d      11       X

For satisfiable : 
                         CVC5-072521-4_d       X       3
                       cvc5-072721-fsr_d      31       X
```

**Comment by ajreynol** [comment]
roughly +20-0 on `PyEx` benchmarks due to being slightly faster, +10-30 on `quad` benchmarks due to missing inferences due to advanced equality rewriting.

**Comment by ajreynol** [comment]
I think we should go ahead and merge, and revisit an independent inference schema that uses extended equality rewriting as a separate module.

**Review by 4tXJ7f — APPROVED** [review]
LGTM

**Pull request merged**
