### PR TITLE
libpoly follows the debug/release of cvc5

### PR DESCRIPTION
**Pull request by Ouyancheng**
I would suggest using the debug build of libpoly in the debug build of cvc5. 
IMPORTANT NOTE: please make sure that ${CMAKE_BUILD_TYPE} referenced here is actually the CMAKE_BUILD_TYPE passed from ./configure.sh. I'm not 100% sure about this.

### CODE REVIEW

**Comment by Ouyancheng** [comment]
Oh ${CMAKE_BUILD_TYPE} is Debug/Production/Test/Competition, not Debug/Release! 
So this might not be a correct way of setting it. 

But as I experimented, it works (don't know why).

**Comment by Ouyancheng** [comment]
This is incorrect. I'm getting a non-debugging build on CMAKE_BUILD_TYPE=Production only because it defaults not to include the debug symbol.

**Comment by mpreiner** [comment]
Note, in general we don't want to compile debug builds for our dependencies if cvc5 is built in debug mode. Dependencies should be used in production mode independent from cvc5's build type.

**Comment by Ouyancheng** [comment]
> Note, in general we don't want to compile debug builds for our dependencies if cvc5 is built in debug mode. Dependencies should be used in production mode independent from cvc5's build type.

OK. I don't mind manually switching it to debug mode if I encounter a problem.

**Pull request closed without merging**
