### PR TITLE
Move cvc5::internal::context to cvc5::context.

### PR DESCRIPTION
**Pull request by mpreiner**

### CODE REVIEW

**Review by ajreynol — COMMENTED** [review]
Do we actually need to rewrite `context::` to `cvc5::context::` when referencing contexts throughout the internal code?

I'd like a solution that doesn't make this verbose.

**Comment by 4tXJ7f** [comment]
> It might be arguable that `context` should stay in `internal`, since 99% of the users of this are internal code.

The problem is that the parser also uses them, so I think that they should be moved to `cvc5::context`.

**Comment by ajreynol** [comment]
Can't we just have the parser use `cvc5::internal::context`?  It seems silly to complicate 95% of our code base for the sake of a few uses in the parser.

**Comment by ajreynol** [comment]
Thinking about this some, I think I would like the rule that code in `cvc5::internal::` has no external dependencies, i.e. it never refers to anything outside of `cvc5::internal::` (one exception perhaps is the cvc5_types file).

**Comment by 4tXJ7f** [comment]
In general, I agree with that, but `cvc5::context` is really more like an external library in my mind. I'd prefer not to see any references to` cvc5::internal` in the parser, because it keeps us honest about not relying on internals in the parser.

**Comment by mpreiner** [comment]
Just for the record: We don't  need the `cvc5::context` prefix anymore, this was merely an artifact of incorrect forward declarations of of context classes, which are now fixed.

**Review by 4tXJ7f — APPROVED** [review]
LGTM

**Pull request merged**
