### PR TITLE
Avoid explicit dependancy on Python 3

### PR DESCRIPTION
**Pull request by ayveejay**
Currently the `mkoptions.py` script explicitly depends on Python 3 -- it can actually be modified to run under Python 2, with some use of the `future`s package.

This PR simply introduces enough of futures to get `mkoptions.py` working via Python 2.

### CODE REVIEW

**Comment by mpreiner** [comment]
Which version of Python 2 had issues with the script? The script should actually already work with Python 2.7.

**Comment by ayveejay** [comment]
@mpreiner yep, you're correct! The only issue is related to the `#!` that explicitly calls `python3`.

I've updated the PR.

**Comment by ayveejay** [comment]
Btw, I am happy to do this in a fresh branch (if you're also happy) to avoid the "commit noise".

**Comment by mpreiner** [comment]
No worries, we can use this PR since we will do a squash commit anyways.

**Pull request merged**
