### PR TITLE
Properly guard sort instantiate

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes https://github.com/cvc5/cvc5-projects/issues/387.

Adds a prefix of that unit test before the first exception.

### CODE REVIEW

**Comment by ajreynol** [comment]
Getting conflicting advice, see https://github.com/cvc5/cvc5/pull/8229#pullrequestreview-900742122 @nafur 
I don't have a strong opinion on this, although I have a slight preference for not having solver_black become enormous.

**Comment by aniemetz** [comment]
I have no problem with an enormous solver_black tbh, at least everything is in one place and I don't have to search in three different files to check if something is already implemented.

If we decide that we want to split out tests for certain things (e.g., datatypes), then we should move all parametric and non-parametric datatypes tests to the appropriate files then.

Opinions @nafur?

**Comment by nafur** [comment]
I don't have a very strong opinion, but would prefer splitting it. My reasons are:
- I generally dislike multi-thousand-LoC files. Also, I'd rather have more tests that run quickly than one test that takes a long time, e.g., when running theses tests with `-j`. Right now it takes ~8s in the dbg CI build, so it's not a pressing issue right now.
- while the number of solver tests used to depend mostly on the size of the API, we now have a regular source of new API tests (murxla), which will make this file grow in the future
- we try to have a consistent set of tests for all APIs, which are the tests in this file right now. As I don't think we want to port these test that come from issues to the other APIs, it would make the task of keeping the "base tests" in sync more difficult

Thus my suggestion would be to have basic tests (that only check whether the API works as intended) in the solver_black and have that one consistent among every API, and then put all the other tests (that originate from issues and thus check for formerly buggy cases) in separate files that are grouped by functionality/theory/...
How aggressive we should split there (i.e. whether "regular" DT and parametric DT should have separate files, or whether linear arith and nonlinear arith shoud)... I don't care.

**Comment by ajreynol** [comment]
I agree with @nafur.  I generally like the idea that `solver_black` represents the "baseline" test of the Solver that exercises all methods, and then project issues are added to other files.

**Comment by aniemetz** [comment]
Right now, we have tests in datatype_black that fall into the category "test the base functionality". If we go with this definition, these should be merged into solver_black.

A personal dislike of files that are several 1000 LOC is not enough IMO. I want to avoid redundancy, or rather, wasted time when trying to figure out what is not yet covered in tests and what is.

Project issue API tests are in a sense regression tests. I want to raise the potential problem that the number of those may get out of hand. I don't see a reason why we should add all of them (we have a tool that will produce these again in case we regress).

Maybe we should take this discussion offline.

**Review by aniemetz — APPROVED** [review]
We will refactor our test infrastructure as discussed offline. LGTM (for now), test will move when refactored.

**Pull request merged**
