### PR TITLE
Remove splitting in nonlinear solver

### PR DESCRIPTION
**Pull request by nafur**
This PR removes some code that splits in the nonlinear solver if the concrete and the abstract models don't match. This is obsolete now.

### CODE REVIEW

**Comment by nafur** [comment]
Benchmarks:
`NRA` +9, `QF_NRA` +2-1, `UFDTNIRA` -1. Still waiting for results on `*NIA*`.

**Comment by nafur** [comment]
> LGTM, assuming the numbers are positive.

Hm: `QF_NIA` +1-6, `QF_UFNIA` -1, `UFNIA` +2-49...

**Comment by ajreynol** [comment]
I believe this is now subsumed by https://github.com/cvc5/cvc5/pull/7787, should this PR be closed?

**Comment by nafur** [comment]
> I believe this is now subsumed by #7787, should this PR be closed?

Yes, it is.

**Pull request closed without merging**
